# Build dotnet core project WF 
# Reuseabled

name: Build dotnet core PRJ

on:
  workflow_call:
    inputs:
      projfile:
        required: true
        type: string

      out_dir:
        required: true
        type: string

      keep_artifact_days:
        required: true
        type: number

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled '
        required: false
        default: true

      projfile:
        required: true
        description: 'csproj file (full)name for build'
        type: string
        default: '服务家对接/服务家对接.csproj'

      out_dir:
        required: true
        description: 'path used for save build result ,and artifact name.'
        type: string
        default: output
      
      keep_artifact_days:
        required: true
        description: 'How many days does the artifact kept.'
        type: number
        default: 0
        

        

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET Core env
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - name: Build
      run: |
        # dotnet restore ${{ inputs.projfile }}
        dotnet publish ${{ inputs.projfile }} -c Release --os linux  --output ${{ inputs.out_dir }}

    - name: Keep Artifact 
      uses: actions/upload-artifact@v3
      with:
        # use the out_dir as default artifact name
        name: ${{ inputs.out_dir }}
        path: ${{ inputs.out_dir }}
        retention-days:  ${{ inputs.keep_artifact_days }}
      if: ${{ inputs.keep_artifact_days > 0 }}


    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false
      timeout-minutes: 30
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}




      


